import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('')

  let lang = 'en';
  let units = 'metric';
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&appid=1a5de708e81cb57509a519910b5221e6&lang=${lang}&units=${units}`;

  const searchLocation = async (event) => {
    if (event.key === 'Enter') {
      axios.get(url)
      .then((response) => {
        console.clear();
        setData(response.data)
        console.log(response.data)
        setWeather(response.data.weather)
        setErrorMessage('')
      }).catch(err =>{
        console.log(err)
        setErrorMessage('Please enter another locations')
        setData({})
        setWeather()
      })
      // const response = await axios.get(`${url}q=${location}&appid=${apikey}&lang=${lang}&units=${units}`);
      // setData(response.data);
      // setWeather(response.data.weather[0].main);
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <input 
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder='Enter Location'
          onKeyDown={searchLocation}
          type='text'
        />
        {errorMessage}
        {
          weather && weather.map((w, index) => {
            return (
            <div key={index} className={styles.content}>
              <h1>The weather in {data.name} is currently {w.description}</h1>
              <h2>With a temp of {data.main.feels_like}°C but it feels like {data.main.temp}°C</h2>
              <h3>and a wind speed of {data.wind.speed}m/s</h3>
              
              </div>
            )
          })
        }
        
      </main>
    </>
  )
}
